/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from 'zod';
import type { Json } from './../../types/database.types';

export const publicRequestStatusSchema = z.enum([
  'pending',
  'active',
  'declined',
]);

export const publicReviewStarsSchema = z.enum(['1', '2', '3', '4', '5']);

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const graphqlPublicGraphqlArgsSchema = z.object({
  extensions: jsonSchema.optional(),
  operationName: z.string().optional(),
  query: z.string().optional(),
  variables: jsonSchema.optional(),
});

export const graphqlPublicGraphqlReturnsSchema = jsonSchema;

export const publicAccommodationTypeRowSchema = z.object({
  createdAt: z.string(),
  displayOrder: z.number(),
  id: z.string(),
  name: z.string(),
  updatedAt: z.string(),
});

export const publicAccommodationTypeInsertSchema = z.object({
  createdAt: z.string().optional(),
  displayOrder: z.number().optional(),
  id: z.string(),
  name: z.string(),
  updatedAt: z.string().optional(),
});

export const publicAccommodationTypeUpdateSchema = z.object({
  createdAt: z.string().optional(),
  displayOrder: z.number().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  updatedAt: z.string().optional(),
});

export const publicAdminUsersRowSchema = z.object({
  createdAt: z.string(),
  userId: z.string(),
});

export const publicAdminUsersInsertSchema = z.object({
  createdAt: z.string().optional(),
  userId: z.string(),
});

export const publicAdminUsersUpdateSchema = z.object({
  createdAt: z.string().optional(),
  userId: z.string().optional(),
});

export const publicChatRowSchema = z.object({
  createdAt: z.string(),
  id: z.string(),
  title: z.string(),
  tripId: z.string().nullable(),
  updatedAt: z.string(),
});

export const publicChatInsertSchema = z.object({
  createdAt: z.string().optional(),
  id: z.string(),
  title: z.string(),
  tripId: z.string().optional().nullable(),
  updatedAt: z.string().optional(),
});

export const publicChatUpdateSchema = z.object({
  createdAt: z.string().optional(),
  id: z.string().optional(),
  title: z.string().optional(),
  tripId: z.string().optional().nullable(),
  updatedAt: z.string().optional(),
});

export const publicChatRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('chat_tripId_trip_id_fk'),
    columns: z.tuple([z.literal('tripId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('searchable_trips'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('chat_tripId_trip_id_fk'),
    columns: z.tuple([z.literal('tripId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('trip'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicChatParticipantRowSchema = z.object({
  chatId: z.string().nullable(),
  createdAt: z.string(),
  id: z.string(),
  updatedAt: z.string(),
  userId: z.string().nullable(),
});

export const publicChatParticipantInsertSchema = z.object({
  chatId: z.string().optional().nullable(),
  createdAt: z.string().optional(),
  id: z.string(),
  updatedAt: z.string().optional(),
  userId: z.string().optional().nullable(),
});

export const publicChatParticipantUpdateSchema = z.object({
  chatId: z.string().optional().nullable(),
  createdAt: z.string().optional(),
  id: z.string().optional(),
  updatedAt: z.string().optional(),
  userId: z.string().optional().nullable(),
});

export const publicChatParticipantRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('chat_participant_chatId_chat_id_fk'),
    columns: z.tuple([z.literal('chatId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('chat'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('chat_participant_userId_user_id_fk'),
    columns: z.tuple([z.literal('userId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('user'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicConversationsRowSchema = z.object({
  created_at: z.string(),
  id: z.string(),
  is_archived_by_user1: z.boolean(),
  is_archived_by_user2: z.boolean(),
  last_message_at: z.string().nullable(),
  updated_at: z.string(),
  user1_id: z.string(),
  user2_id: z.string(),
});

export const publicConversationsInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  is_archived_by_user1: z.boolean().optional(),
  is_archived_by_user2: z.boolean().optional(),
  last_message_at: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  user1_id: z.string(),
  user2_id: z.string(),
});

export const publicConversationsUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  is_archived_by_user1: z.boolean().optional(),
  is_archived_by_user2: z.boolean().optional(),
  last_message_at: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  user1_id: z.string().optional(),
  user2_id: z.string().optional(),
});

export const publicConversationsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('conversations_user1_id_fkey'),
    columns: z.tuple([z.literal('user1_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('user'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('conversations_user2_id_fkey'),
    columns: z.tuple([z.literal('user2_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('user'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicEmailNotificationsRowSchema = z.object({
  body: z.string(),
  created_at: z.string().nullable(),
  error_message: z.string().nullable(),
  id: z.string(),
  recipient_email: z.string(),
  recipient_name: z.string().nullable(),
  sent_at: z.string().nullable(),
  status: z.string().nullable(),
  subject: z.string(),
  updated_at: z.string().nullable(),
});

export const publicEmailNotificationsInsertSchema = z.object({
  body: z.string(),
  created_at: z.string().optional().nullable(),
  error_message: z.string().optional().nullable(),
  id: z.string().optional(),
  recipient_email: z.string(),
  recipient_name: z.string().optional().nullable(),
  sent_at: z.string().optional().nullable(),
  status: z.string().optional().nullable(),
  subject: z.string(),
  updated_at: z.string().optional().nullable(),
});

export const publicEmailNotificationsUpdateSchema = z.object({
  body: z.string().optional(),
  created_at: z.string().optional().nullable(),
  error_message: z.string().optional().nullable(),
  id: z.string().optional(),
  recipient_email: z.string().optional(),
  recipient_name: z.string().optional().nullable(),
  sent_at: z.string().optional().nullable(),
  status: z.string().optional().nullable(),
  subject: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicHiddenTripsRowSchema = z.object({
  createdAt: z.string(),
  tripId: z.string(),
});

export const publicHiddenTripsInsertSchema = z.object({
  createdAt: z.string().optional(),
  tripId: z.string(),
});

export const publicHiddenTripsUpdateSchema = z.object({
  createdAt: z.string().optional(),
  tripId: z.string().optional(),
});

export const publicHiddenTripsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('hidden_trips_tripId_fkey'),
    columns: z.tuple([z.literal('tripId')]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal('searchable_trips'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('hidden_trips_tripId_fkey'),
    columns: z.tuple([z.literal('tripId')]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal('trip'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicLocationRowSchema = z.object({
  city: z.string(),
  country: z.string(),
  countryCode: z.string(),
  createdAt: z.string(),
  displayName: z.string(),
  id: z.string(),
  latitude: z.number().nullable(),
  longitude: z.number().nullable(),
  region: z.string().nullable(),
  updatedAt: z.string(),
});

export const publicLocationInsertSchema = z.object({
  city: z.string(),
  country: z.string(),
  countryCode: z.string(),
  createdAt: z.string().optional(),
  displayName: z.string(),
  id: z.string().optional(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  region: z.string().optional().nullable(),
  updatedAt: z.string().optional(),
});

export const publicLocationUpdateSchema = z.object({
  city: z.string().optional(),
  country: z.string().optional(),
  countryCode: z.string().optional(),
  createdAt: z.string().optional(),
  displayName: z.string().optional(),
  id: z.string().optional(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  region: z.string().optional().nullable(),
  updatedAt: z.string().optional(),
});

export const publicMessageRowSchema = z.object({
  chatId: z.string().nullable(),
  content: z.string(),
  createdAt: z.string(),
  id: z.string(),
  participantId: z.string().nullable(),
  updatedAt: z.string(),
});

export const publicMessageInsertSchema = z.object({
  chatId: z.string().optional().nullable(),
  content: z.string(),
  createdAt: z.string().optional(),
  id: z.string(),
  participantId: z.string().optional().nullable(),
  updatedAt: z.string().optional(),
});

export const publicMessageUpdateSchema = z.object({
  chatId: z.string().optional().nullable(),
  content: z.string().optional(),
  createdAt: z.string().optional(),
  id: z.string().optional(),
  participantId: z.string().optional().nullable(),
  updatedAt: z.string().optional(),
});

export const publicMessageRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('message_chatId_chat_id_fk'),
    columns: z.tuple([z.literal('chatId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('chat'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('message_participantId_chat_participant_id_fk'),
    columns: z.tuple([z.literal('participantId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('chat_participant'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicMessageDeliveryLogRowSchema = z.object({
  event_type: z.string(),
  id: z.string(),
  message_id: z.string().nullable(),
  metadata: jsonSchema.nullable(),
  timestamp: z.string(),
  user_id: z.string().nullable(),
});

export const publicMessageDeliveryLogInsertSchema = z.object({
  event_type: z.string(),
  id: z.string().optional(),
  message_id: z.string().optional().nullable(),
  metadata: jsonSchema.optional().nullable(),
  timestamp: z.string().optional(),
  user_id: z.string().optional().nullable(),
});

export const publicMessageDeliveryLogUpdateSchema = z.object({
  event_type: z.string().optional(),
  id: z.string().optional(),
  message_id: z.string().optional().nullable(),
  metadata: jsonSchema.optional().nullable(),
  timestamp: z.string().optional(),
  user_id: z.string().optional().nullable(),
});

export const publicMessageDeliveryLogRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('message_delivery_log_message_id_fkey'),
    columns: z.tuple([z.literal('message_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('messages'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('message_delivery_log_user_id_fkey'),
    columns: z.tuple([z.literal('user_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('user'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicMessageReadStatusRowSchema = z.object({
  id: z.string(),
  message_id: z.string(),
  read_at: z.string(),
  user_id: z.string(),
});

export const publicMessageReadStatusInsertSchema = z.object({
  id: z.string().optional(),
  message_id: z.string(),
  read_at: z.string().optional(),
  user_id: z.string(),
});

export const publicMessageReadStatusUpdateSchema = z.object({
  id: z.string().optional(),
  message_id: z.string().optional(),
  read_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicMessageReadStatusRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('message_read_status_message_id_fkey'),
    columns: z.tuple([z.literal('message_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('messages'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('message_read_status_user_id_fkey'),
    columns: z.tuple([z.literal('user_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('user'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicMessagesRowSchema = z.object({
  content: z.string(),
  conversation_id: z.string(),
  created_at: z.string(),
  deleted_at: z.string().nullable(),
  edited_at: z.string().nullable(),
  id: z.string(),
  message_type: z.string().nullable(),
  metadata: jsonSchema.nullable(),
  sender_id: z.string(),
  updated_at: z.string().nullable(),
});

export const publicMessagesInsertSchema = z.object({
  content: z.string(),
  conversation_id: z.string(),
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  edited_at: z.string().optional().nullable(),
  id: z.string().optional(),
  message_type: z.string().optional().nullable(),
  metadata: jsonSchema.optional().nullable(),
  sender_id: z.string(),
  updated_at: z.string().optional().nullable(),
});

export const publicMessagesUpdateSchema = z.object({
  content: z.string().optional(),
  conversation_id: z.string().optional(),
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  edited_at: z.string().optional().nullable(),
  id: z.string().optional(),
  message_type: z.string().optional().nullable(),
  metadata: jsonSchema.optional().nullable(),
  sender_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicMessagesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('messages_conversation_id_fkey'),
    columns: z.tuple([z.literal('conversation_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('conversations'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('messages_sender_id_fkey'),
    columns: z.tuple([z.literal('sender_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('user'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicMessagingPerformanceLogRowSchema = z.object({
  conversation_id: z.string().nullable(),
  duration_ms: z.number(),
  id: z.string(),
  metadata: jsonSchema.nullable(),
  operation: z.string(),
  timestamp: z.string(),
  user_id: z.string().nullable(),
});

export const publicMessagingPerformanceLogInsertSchema = z.object({
  conversation_id: z.string().optional().nullable(),
  duration_ms: z.number(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  operation: z.string(),
  timestamp: z.string().optional(),
  user_id: z.string().optional().nullable(),
});

export const publicMessagingPerformanceLogUpdateSchema = z.object({
  conversation_id: z.string().optional().nullable(),
  duration_ms: z.number().optional(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  operation: z.string().optional(),
  timestamp: z.string().optional(),
  user_id: z.string().optional().nullable(),
});

export const publicMessagingPerformanceLogRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('messaging_performance_log_conversation_id_fkey'),
    columns: z.tuple([z.literal('conversation_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('conversations'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('messaging_performance_log_user_id_fkey'),
    columns: z.tuple([z.literal('user_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('user'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicRequestRowSchema = z.object({
  createdAt: z.string(),
  id: z.string(),
  message: z.string().nullable(),
  status: publicRequestStatusSchema.nullable(),
  tripId: z.string().nullable(),
  updatedAt: z.string(),
  userId: z.string().nullable(),
});

export const publicRequestInsertSchema = z.object({
  createdAt: z.string().optional(),
  id: z.string().optional(),
  message: z.string().optional().nullable(),
  status: publicRequestStatusSchema.optional().nullable(),
  tripId: z.string().optional().nullable(),
  updatedAt: z.string().optional(),
  userId: z.string().optional().nullable(),
});

export const publicRequestUpdateSchema = z.object({
  createdAt: z.string().optional(),
  id: z.string().optional(),
  message: z.string().optional().nullable(),
  status: publicRequestStatusSchema.optional().nullable(),
  tripId: z.string().optional().nullable(),
  updatedAt: z.string().optional(),
  userId: z.string().optional().nullable(),
});

export const publicRequestRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('request_tripid_fkey'),
    columns: z.tuple([z.literal('tripId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('searchable_trips'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('request_tripid_fkey'),
    columns: z.tuple([z.literal('tripId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('trip'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('request_userId_fkey'),
    columns: z.tuple([z.literal('userId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('user'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicReviewRowSchema = z.object({
  comment: z.string(),
  createdAt: z.string(),
  id: z.string(),
  imageUrl: z.string().nullable(),
  revieweeId: z.string().nullable(),
  reviewerId: z.string().nullable(),
  stars: publicReviewStarsSchema,
  tripId: z.string().nullable(),
  updatedAt: z.string(),
});

export const publicReviewInsertSchema = z.object({
  comment: z.string(),
  createdAt: z.string().optional(),
  id: z.string().optional(),
  imageUrl: z.string().optional().nullable(),
  revieweeId: z.string().optional().nullable(),
  reviewerId: z.string().optional().nullable(),
  stars: publicReviewStarsSchema,
  tripId: z.string().optional().nullable(),
  updatedAt: z.string().optional(),
});

export const publicReviewUpdateSchema = z.object({
  comment: z.string().optional(),
  createdAt: z.string().optional(),
  id: z.string().optional(),
  imageUrl: z.string().optional().nullable(),
  revieweeId: z.string().optional().nullable(),
  reviewerId: z.string().optional().nullable(),
  stars: publicReviewStarsSchema.optional(),
  tripId: z.string().optional().nullable(),
  updatedAt: z.string().optional(),
});

export const publicReviewRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('review_revieweeId_fkey'),
    columns: z.tuple([z.literal('revieweeId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('user'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('review_reviewerId_fkey'),
    columns: z.tuple([z.literal('reviewerId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('user'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('review_tripid_fkey'),
    columns: z.tuple([z.literal('tripId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('searchable_trips'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('review_tripid_fkey'),
    columns: z.tuple([z.literal('tripId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('trip'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicRoleRowSchema = z.object({
  created_at: z.string(),
  description: z.string().nullable(),
  display_name: z.string(),
  id: z.string(),
  level: z.number(),
  name: z.string(),
  updated_at: z.string(),
});

export const publicRoleInsertSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  display_name: z.string(),
  id: z.string().optional(),
  level: z.number().optional(),
  name: z.string(),
  updated_at: z.string().optional(),
});

export const publicRoleUpdateSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  display_name: z.string().optional(),
  id: z.string().optional(),
  level: z.number().optional(),
  name: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicRoomRowSchema = z.object({
  created_at: z.string(),
  description: z.string().nullable(),
  id: z.string(),
  name: z.string(),
  occupant_id: z.string().nullable(),
  pictures: z.array(z.string()).nullable(),
  updated_at: z.string(),
  villa_id: z.string(),
});

export const publicRoomInsertSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string(),
  occupant_id: z.string().optional().nullable(),
  pictures: z.array(z.string()).optional().nullable(),
  updated_at: z.string().optional(),
  villa_id: z.string(),
});

export const publicRoomUpdateSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  occupant_id: z.string().optional().nullable(),
  pictures: z.array(z.string()).optional().nullable(),
  updated_at: z.string().optional(),
  villa_id: z.string().optional(),
});

export const publicRoomRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('room_villa_id_fkey'),
    columns: z.tuple([z.literal('villa_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('villa'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicRoomRequestRowSchema = z.object({
  created_at: z.string(),
  id: z.string(),
  message: z.string().nullable(),
  room_id: z.string(),
  status: z.string().nullable(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const publicRoomRequestInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  message: z.string().optional().nullable(),
  room_id: z.string(),
  status: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const publicRoomRequestUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  message: z.string().optional().nullable(),
  room_id: z.string().optional(),
  status: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicRoomRequestRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('room_request_room_id_fkey'),
    columns: z.tuple([z.literal('room_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('room'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicTripRowSchema = z.object({
  accommodationTypeId: z.string().nullable(),
  bookingUrl: z.string().nullable(),
  createdAt: z.string(),
  description: z.string(),
  endDate: z.string().nullable(),
  estimatedMonth: z.string().nullable(),
  estimatedYear: z.string().nullable(),
  flexible: z.boolean(),
  hostId: z.string().nullable(),
  id: z.string(),
  isPublic: z.boolean().nullable(),
  joineeId: z.string().nullable(),
  location: z.string(),
  locationId: z.string().nullable(),
  matchWith: z.string().nullable(),
  name: z.string(),
  numberOfRooms: z.number().nullable(),
  personalNote: z.string().nullable(),
  rooms: jsonSchema.nullable(),
  startDate: z.string().nullable(),
  thumbnailUrl: z.string().nullable(),
  tripLink: z.string().nullable(),
  updatedAt: z.string(),
  vibe: z.string().nullable(),
});

export const publicTripInsertSchema = z.object({
  accommodationTypeId: z.string().optional().nullable(),
  bookingUrl: z.string().optional().nullable(),
  createdAt: z.string().optional(),
  description: z.string(),
  endDate: z.string().optional().nullable(),
  estimatedMonth: z.string().optional().nullable(),
  estimatedYear: z.string().optional().nullable(),
  flexible: z.boolean().optional(),
  hostId: z.string().optional().nullable(),
  id: z.string().optional(),
  isPublic: z.boolean().optional().nullable(),
  joineeId: z.string().optional().nullable(),
  location: z.string(),
  locationId: z.string().optional().nullable(),
  matchWith: z.string().optional().nullable(),
  name: z.string(),
  numberOfRooms: z.number().optional().nullable(),
  personalNote: z.string().optional().nullable(),
  rooms: jsonSchema.optional().nullable(),
  startDate: z.string().optional().nullable(),
  thumbnailUrl: z.string().optional().nullable(),
  tripLink: z.string().optional().nullable(),
  updatedAt: z.string().optional(),
  vibe: z.string().optional().nullable(),
});

export const publicTripUpdateSchema = z.object({
  accommodationTypeId: z.string().optional().nullable(),
  bookingUrl: z.string().optional().nullable(),
  createdAt: z.string().optional(),
  description: z.string().optional(),
  endDate: z.string().optional().nullable(),
  estimatedMonth: z.string().optional().nullable(),
  estimatedYear: z.string().optional().nullable(),
  flexible: z.boolean().optional(),
  hostId: z.string().optional().nullable(),
  id: z.string().optional(),
  isPublic: z.boolean().optional().nullable(),
  joineeId: z.string().optional().nullable(),
  location: z.string().optional(),
  locationId: z.string().optional().nullable(),
  matchWith: z.string().optional().nullable(),
  name: z.string().optional(),
  numberOfRooms: z.number().optional().nullable(),
  personalNote: z.string().optional().nullable(),
  rooms: jsonSchema.optional().nullable(),
  startDate: z.string().optional().nullable(),
  thumbnailUrl: z.string().optional().nullable(),
  tripLink: z.string().optional().nullable(),
  updatedAt: z.string().optional(),
  vibe: z.string().optional().nullable(),
});

export const publicTripRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('trip_accommodation_type_id_fkey'),
    columns: z.tuple([z.literal('accommodationTypeId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('accommodation_type'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('trip_hostId_fkey'),
    columns: z.tuple([z.literal('hostId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('user'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('trip_joineeId_fkey'),
    columns: z.tuple([z.literal('joineeId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('user'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('trip_locationId_fkey'),
    columns: z.tuple([z.literal('locationId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('location'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicUserRowSchema = z.object({
  bio: z.string().nullable(),
  birthPlace: z.string().nullable(),
  createdAt: z.string(),
  currentPlace: z.string().nullable(),
  dayOfBirth: z.number().nullable(),
  email: z.string(),
  fullName: z.string().nullable(),
  gender: z.string().nullable(),
  id: z.string(),
  imageUrl: z.string().nullable(),
  instagramUrl: z.string().nullable(),
  languages: jsonSchema.nullable(),
  learningLanguages: jsonSchema.nullable(),
  monthOfBirth: z.number().nullable(),
  mostInfluencedCountry: z.string().nullable(),
  mostInfluencedCountryDescription: z.string().nullable(),
  mostInfluencedExperience: z.string().nullable(),
  name: z.string().nullable(),
  personalizedLink: z.string().nullable(),
  profileCreated: z.boolean().nullable(),
  profilePicture: z.string().nullable(),
  role_id: z.string().nullable(),
  shareModalShown: z.boolean().nullable(),
  travelPhotos: jsonSchema.nullable(),
  travelTraits: jsonSchema.nullable(),
  updatedAt: z.string(),
  whatsapp: z.string().nullable(),
  yearOfBirth: z.number().nullable(),
});

export const publicUserInsertSchema = z.object({
  bio: z.string().optional().nullable(),
  birthPlace: z.string().optional().nullable(),
  createdAt: z.string().optional(),
  currentPlace: z.string().optional().nullable(),
  dayOfBirth: z.number().optional().nullable(),
  email: z.string(),
  fullName: z.string().optional().nullable(),
  gender: z.string().optional().nullable(),
  id: z.string(),
  imageUrl: z.string().optional().nullable(),
  instagramUrl: z.string().optional().nullable(),
  languages: jsonSchema.optional().nullable(),
  learningLanguages: jsonSchema.optional().nullable(),
  monthOfBirth: z.number().optional().nullable(),
  mostInfluencedCountry: z.string().optional().nullable(),
  mostInfluencedCountryDescription: z.string().optional().nullable(),
  mostInfluencedExperience: z.string().optional().nullable(),
  name: z.string().optional().nullable(),
  personalizedLink: z.string().optional().nullable(),
  profileCreated: z.boolean().optional().nullable(),
  profilePicture: z.string().optional().nullable(),
  role_id: z.string().optional().nullable(),
  shareModalShown: z.boolean().optional().nullable(),
  travelPhotos: jsonSchema.optional().nullable(),
  travelTraits: jsonSchema.optional().nullable(),
  updatedAt: z.string().optional(),
  whatsapp: z.string().optional().nullable(),
  yearOfBirth: z.number().optional().nullable(),
});

export const publicUserUpdateSchema = z.object({
  bio: z.string().optional().nullable(),
  birthPlace: z.string().optional().nullable(),
  createdAt: z.string().optional(),
  currentPlace: z.string().optional().nullable(),
  dayOfBirth: z.number().optional().nullable(),
  email: z.string().optional(),
  fullName: z.string().optional().nullable(),
  gender: z.string().optional().nullable(),
  id: z.string().optional(),
  imageUrl: z.string().optional().nullable(),
  instagramUrl: z.string().optional().nullable(),
  languages: jsonSchema.optional().nullable(),
  learningLanguages: jsonSchema.optional().nullable(),
  monthOfBirth: z.number().optional().nullable(),
  mostInfluencedCountry: z.string().optional().nullable(),
  mostInfluencedCountryDescription: z.string().optional().nullable(),
  mostInfluencedExperience: z.string().optional().nullable(),
  name: z.string().optional().nullable(),
  personalizedLink: z.string().optional().nullable(),
  profileCreated: z.boolean().optional().nullable(),
  profilePicture: z.string().optional().nullable(),
  role_id: z.string().optional().nullable(),
  shareModalShown: z.boolean().optional().nullable(),
  travelPhotos: jsonSchema.optional().nullable(),
  travelTraits: jsonSchema.optional().nullable(),
  updatedAt: z.string().optional(),
  whatsapp: z.string().optional().nullable(),
  yearOfBirth: z.number().optional().nullable(),
});

export const publicUserRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('user_role_id_fkey'),
    columns: z.tuple([z.literal('role_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('role'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicUserPresenceRowSchema = z.object({
  device_info: jsonSchema.nullable(),
  is_online: z.boolean(),
  last_seen_at: z.string(),
  typing_in_conversation_id: z.string().nullable(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const publicUserPresenceInsertSchema = z.object({
  device_info: jsonSchema.optional().nullable(),
  is_online: z.boolean().optional(),
  last_seen_at: z.string().optional(),
  typing_in_conversation_id: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const publicUserPresenceUpdateSchema = z.object({
  device_info: jsonSchema.optional().nullable(),
  is_online: z.boolean().optional(),
  last_seen_at: z.string().optional(),
  typing_in_conversation_id: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicUserPresenceRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('user_presence_typing_in_conversation_id_fkey'),
    columns: z.tuple([z.literal('typing_in_conversation_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('conversations'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('user_presence_user_id_fkey'),
    columns: z.tuple([z.literal('user_id')]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal('user'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicVillaRowSchema = z.object({
  created_at: z.string(),
  created_by: z.string().nullable(),
  description: z.string().nullable(),
  id: z.string(),
  location: z.string(),
  location_id: z.string().nullable(),
  name: z.string(),
  pictures: z.array(z.string()).nullable(),
  updated_at: z.string(),
});

export const publicVillaInsertSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  location: z.string(),
  location_id: z.string().optional().nullable(),
  name: z.string(),
  pictures: z.array(z.string()).optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicVillaUpdateSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  location: z.string().optional(),
  location_id: z.string().optional().nullable(),
  name: z.string().optional(),
  pictures: z.array(z.string()).optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicVillaRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('villa_location_id_fkey'),
    columns: z.tuple([z.literal('location_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('location'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicSearchableTripsRowSchema = z.object({
  accommodationTypeId: z.string().nullable(),
  bookingUrl: z.string().nullable(),
  createdAt: z.string().nullable(),
  description: z.string().nullable(),
  endDate: z.string().nullable(),
  estimatedMonth: z.string().nullable(),
  estimatedYear: z.string().nullable(),
  flexible: z.boolean().nullable(),
  hostId: z.string().nullable(),
  id: z.string().nullable(),
  isPublic: z.boolean().nullable(),
  joineeId: z.string().nullable(),
  location: z.string().nullable(),
  locationId: z.string().nullable(),
  matchWith: z.string().nullable(),
  name: z.string().nullable(),
  numberOfRooms: z.number().nullable(),
  personalNote: z.string().nullable(),
  rooms: jsonSchema.nullable(),
  startDate: z.string().nullable(),
  thumbnailUrl: z.string().nullable(),
  tripLink: z.string().nullable(),
  updatedAt: z.string().nullable(),
  vibe: z.string().nullable(),
});

export const publicSearchableTripsInsertSchema = z.object({
  accommodationTypeId: z.string().optional().nullable(),
  bookingUrl: z.string().optional().nullable(),
  createdAt: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  endDate: z.string().optional().nullable(),
  estimatedMonth: z.string().optional().nullable(),
  estimatedYear: z.string().optional().nullable(),
  flexible: z.boolean().optional().nullable(),
  hostId: z.string().optional().nullable(),
  id: z.string().optional().nullable(),
  isPublic: z.boolean().optional().nullable(),
  joineeId: z.string().optional().nullable(),
  location: z.string().optional().nullable(),
  locationId: z.string().optional().nullable(),
  matchWith: z.string().optional().nullable(),
  name: z.string().optional().nullable(),
  numberOfRooms: z.number().optional().nullable(),
  personalNote: z.string().optional().nullable(),
  rooms: jsonSchema.optional().nullable(),
  startDate: z.string().optional().nullable(),
  thumbnailUrl: z.string().optional().nullable(),
  tripLink: z.string().optional().nullable(),
  updatedAt: z.string().optional().nullable(),
  vibe: z.string().optional().nullable(),
});

export const publicSearchableTripsUpdateSchema = z.object({
  accommodationTypeId: z.string().optional().nullable(),
  bookingUrl: z.string().optional().nullable(),
  createdAt: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  endDate: z.string().optional().nullable(),
  estimatedMonth: z.string().optional().nullable(),
  estimatedYear: z.string().optional().nullable(),
  flexible: z.boolean().optional().nullable(),
  hostId: z.string().optional().nullable(),
  id: z.string().optional().nullable(),
  isPublic: z.boolean().optional().nullable(),
  joineeId: z.string().optional().nullable(),
  location: z.string().optional().nullable(),
  locationId: z.string().optional().nullable(),
  matchWith: z.string().optional().nullable(),
  name: z.string().optional().nullable(),
  numberOfRooms: z.number().optional().nullable(),
  personalNote: z.string().optional().nullable(),
  rooms: jsonSchema.optional().nullable(),
  startDate: z.string().optional().nullable(),
  thumbnailUrl: z.string().optional().nullable(),
  tripLink: z.string().optional().nullable(),
  updatedAt: z.string().optional().nullable(),
  vibe: z.string().optional().nullable(),
});

export const publicSearchableTripsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('trip_accommodation_type_id_fkey'),
    columns: z.tuple([z.literal('accommodationTypeId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('accommodation_type'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('trip_hostId_fkey'),
    columns: z.tuple([z.literal('hostId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('user'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('trip_joineeId_fkey'),
    columns: z.tuple([z.literal('joineeId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('user'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('trip_locationId_fkey'),
    columns: z.tuple([z.literal('locationId')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('location'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
]);

export const publicGetUnreadMessageCountArgsSchema = z.object({
  p_conversation_id: z.string(),
  p_user_id: z.string(),
});

export const publicGetUnreadMessageCountReturnsSchema = z.number();

export const publicIsUserOnlineArgsSchema = z.object({
  p_user_id: z.string(),
});

export const publicIsUserOnlineReturnsSchema = z.boolean();

export const publicMarkMessagesAsReadArgsSchema = z.object({
  p_conversation_id: z.string(),
});

export const publicMarkMessagesAsReadReturnsSchema = z.undefined();
