export { HomePage } from './HomePage'
export { LoginPage } from './LoginPage'
export { SignupPage } from './SignupPage'
export { ForgotPasswordPage } from './ForgotPasswordPage'
export { ResetPasswordPage } from './ResetPasswordPage'
export { DashboardPage } from './DashboardPage'
export { default as TermsPage } from './TermsPage'
export { default as PrivacyPage } from './PrivacyPage'
export { default as HowItWorks } from './HowItWorks'